In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
vg = pd.read_csv('vgsales.csv')
vg

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [21]:
vg.groupby("Year").mean()

                Rank  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
Year
1980.0   3314.000000  1.176667  0.074444  0.000000     0.013333      1.264444
1981.0   4141.043478  0.726087  0.042609  0.000000     0.006957      0.777609
1982.0   4144.055556  0.747778  0.045833  0.000000     0.008611      0.801667
1983.0   3338.764706  0.456471  0.047059  0.476471     0.008235      0.987647
1984.0   1636.500000  2.377143  0.150000  1.019286     0.050000      3.597143
1985.0   3964.642857  2.409286  0.338571  1.040000     0.065714      3.852857
1986.0   1713.619048  0.595238  0.135238  0.943333     0.091905      1.765238
1987.0   3418.812500  0.528750  0.088125  0.726875     0.012500      1.358750
1988.0   2478.733333  1.591333  0.439333  1.050667     0.066000      3.148000
1989.0   2362.117647  2.655882  0.496471  1.080000     0.088235      4.320588
1990.0   1569.125000  1.591250  0.476875  0.930000     0.087500      3.086875
1991.0   5190.756098  0.311220  0.096341  0.360488     0.018049      0.786098
1992.0   4858.744186  0.787674  0.272326  0.672326     0.038372      1.771163
1993.0   6312.700000  0.252000  0.077500  0.422167     0.014833      0.766333
1994.0   7180.917355  0.232645  0.122975  0.280909     0.018182      0.654298
1995.0   8582.621005  0.113333  0.068037  0.208904     0.012055      0.402329
1996.0   7268.714829  0.329886  0.179696  0.218403     0.029240      0.757224
1997.0   6563.937716  0.327855  0.167197  0.169100     0.031592      0.695433
1998.0   6922.137203  0.338681  0.176517  0.132032     0.029103      0.676702
1999.0   6470.544379  0.372959  0.185414  0.154852     0.029734      0.743402
2000.0   6809.088825  0.270745  0.151146  0.122550     0.033295      0.577536
2001.0   7026.493776  0.360954  0.196867  0.082697     0.047220      0.687697
2002.0   8239.068758  0.260784  0.132376  0.050374     0.032907      0.477105
2003.0   7885.154839  0.249794  0.133948  0.044129     0.033561      0.461742
2004.0   7615.169069  0.291730  0.140655  0.054587     0.061979      0.549554
2005.0   8213.027630  0.257821  0.129586  0.057683     0.043124      0.488778
2006.0   9487.691468  0.261032  0.128214  0.073145     0.053998      0.516905
2007.0   8606.163894  0.259609  0.133527  0.050158     0.064559      0.508428
2008.0   8464.990896  0.246106  0.129132  0.042199     0.057696      0.475420
2009.0   8679.398323  0.236792  0.133885  0.043249     0.052250      0.466317
2010.0   8783.959492  0.241652  0.140373  0.047252     0.047577      0.476926
2011.0   8794.941176  0.211642  0.147006  0.046567     0.047752      0.453020
2012.0   8455.035008  0.235860  0.180791  0.078752     0.057565      0.553333
2013.0   8055.597070  0.283462  0.230403  0.087161     0.072930      0.674194
2014.0   8319.225086  0.226753  0.215893  0.067801     0.068763      0.579124
2015.0   9797.796417  0.167459  0.159137  0.054919     0.048876      0.430684
2016.0  11429.244186  0.065872  0.077791  0.039826     0.022529      0.206192
2017.0  15692.666667  0.000000  0.000000  0.016667     0.000000      0.016667
2020.0   5959.000000  0.270000  0.000000  0.000000     0.020000      0.290000